language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -f ./client/Dockerfile.dev -t complex-frontend:test ./client

script:
  - docker run -e CI=true complex-frontend:test npm run test

after_success:
  - docker build -t abhishekkalahal/complex-client ./client
  - docker build -t abhishekkalahal/complex-server ./server
  - docker build -t abhishekkalahal/complex-worker ./worker
  - docker build -t abhishekkalahal/complex-nginx ./nginx
  - echo "$docker_password" | docker login -u "$docker_uname" --password-stdin
  - docker push abhishekkalahal/complex-client
  - docker push abhishekkalahal/complex-server
  - docker push abhishekkalahal/complex-worker
  - docker push abhishekkalahal/complex-nginx

deploy:
  provider: elasticbeanstalk
  region: 'ap-south-1'
  app: 'complex'
  env: 'Complex-env'
  bucket_name: 'elasticbeanstalk-ap-south-1-740362156262'
  bucket_path: 'complex'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY